[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "conflict_detection"
version = "0.1.0"
description = "Computer Vision system coupled with GIS analysis for identifying, cataloguing, and evaluating traffic conflict events."
readme = "README.md"
requires-python = ">=3.8"
license = "GPL-3.0-only"
authors = [
    {name = "Shane Teel"}
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Operating System :: OS Independent"
]
dependencies = [
    "ultralytics>=8.0.0",
    "opencv-python>=4.8.0",
    "numpy>=1.24.0",
    "supervision==0.27.0",
    "utm>=0.8.1",
    "folium>=0.20.0"
]

[project.urls]
Homepage = "https://github.com/ShaneTeel/traffic-conflict-detection"

[tool.setuptools.packages.find]
where = ["."]
include = ["*"]
exclude = ["tests*"]